Fix for eclipse 4.6
benelog/multiline pull request #15
Opened 2017-03-07 02:25 UTC by rimmeraj

This allows multiline to work in eclipse 4.6. They changed the classloading so it does not expose the internal classes , we created a custom classloader that can see the internal classes and the mutlline class

2017-03-09 01:29 UTC, jihwan requested changes
shoud it change synchoronized methods? ProxyClassLoader.loadClass()

2017-03-09 01:38 UTC, benelog commented
@rimmeraj 
Thank you for the PR.
I'll review it on this weekend.

2017-03-13 21:37 UTC, benelog commented on multiline-string/src/main/java/org/adrianwalker/multilinestring/MultilineProcessor.java
> +	      synchronized (getClassLoadingLock(name)) {
@jihwan 
I will consider it after merging this PR.

2017-03-13 21:37 UTC, merged

2017-03-16 00:50 UTC, jihwan reviewed
This grammer(Catching Multiple Exception Types) is available jdk7.

2017-03-16 00:50 UTC, jihwan commented on multiline-string/src/main/java/org/adrianwalker/multilinestring/MultilineProcessor.java
> +		  	catch (InstantiationException | IllegalAccessException | ClassNotFoundException e)
This grammer is available jdk7.